name: CI
on:
  workflow_dispatch:
  schedule: [{cron: '00 16 * * *'}]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.10'}
      - name: Install
        run: pip install -r requirements.txt -q
      - name: Set Env
        run: |
          echo "PROFILES<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.PROFILES }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "PUSH_CONFIG<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.PUSH_CONFIG }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Run
        run: |
          python utils.py > /dev/null 2>&1 || exit 1
      - name: Cleanup
        if: always()
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
